service: Hectare.Platform.Services.Inventory.Assets

frameworkVersion: '2'

useDotenv: false

# You're relying on provider plugin which doesn't provide a validation schema for its config. Turn off the warning here.
configValidationMode: off

# load the environment configuration from the correct function in config.js which in turn loads the
# full app config from the core configuration module using the encryption key in environment variables
# to decrypt the relevant keys for this environment. Config values can be referenced in the file using ${self:custom.property_name}
custom: 
  # settings: ${file(../../config.js):${opt:stage, 'live'}}
  serverless-offline:
    httpPort: 8001
    lambdaPort: 4006
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  endpointType: REGIONAL
  stage: dev # ${opt:stage, 'dev'}
  region: eu-west-2
  memorySize: 1024
  timeout: 30
  apiGateway:
    shouldStartNameWithService: true
  # environment: 
  #   HECTARE: ${self:custom.settings.environment}

plugins:
  - serverless-offline

functions:
  api:
    handler: index.api_handler
    events:
      - http:
          path: /assets/{proxy+}
          method: ANY

  events:
    handler: index.event_handler
    events:
      - eventBridge:
          eventBus: ${self:custom.settings.event_bridge_bus}
          pattern:
            source:
              - ${self:custom.settings.event_bridge_source}
            detail-type:
              - ASSET_CREATED
