service: assets

frameworkVersion: '2'

useDotenv: false

# You're relying on provider plugin which doesn't provide a validation schema for its config. Turn off the warning here.
configValidationMode: off

# load the environment configuration from the correct function in config.js which in turn loads the
# full app config from the core configuration module using the encryption key in environment variables
# to decrypt the relevant keys for this environment. Config values can be referenced in the file using ${self:custom.property_name}
custom: 
  settings: ${file(../../config.js):${opt:stage, 'live'}}
  prune:
    automatic: true
    includeLayers: true
    number: 3
  serverless-offline:
    httpPort: 3006
    lambdaPort: 4006
    prefix: geo
    noPrependStageInUrl: true
  optimize:
    debug: false
    minify: false
    exclude:
      - aws-sdk
  serverless-offline-aws-eventbridge:
    port: 8006 # port to run the eventBridge mock server on
    mockEventBridgeServer: true # Set to false if EventBridge is already mocked by another stack
    pubSubPort: 9006 # Port to run the MQ server (or just listen if using an EventBridge Mock server from another stack)
    debug: false # flag to show debug messages
    account: '974611314441' # account id that gets passed to the event
    maximumRetryAttempts: 10 # maximumRetryAttempts to retry lambda
    retryDelayMs: 500 # retry delay

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  memorySize: 1024
  timeout: 30
  apiGateway:
    shouldStartNameWithService: true
  environment: 
    HECTARE: ${self:custom.settings.environment}

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline-aws-eventbridge
  - serverless-offline

package:
  individually: true
  exclude:
    - '**/*'
  include:
    - 'src/**/*.yml'

functions:
  api:
    handler: index.api_handler
    package:
      include:
        - ./index.ts
    events:
      - http:
          path: /assets
          method: ANY
          cors:
            headers:
              - x-platform-key
              - x-platform-key-override
              - x-platform-secret
              - x-platform-maintenance
              - x-platform-location
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
      - http:
          path: /assets/{proxy+}
          method: ANY
          cors:
            headers:
              - x-platform-key
              - x-platform-key-override
              - x-platform-secret
              - x-platform-maintenance
              - x-platform-location
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

  events:
    handler: index.event_handler
    package:
      include:
        - ./index.ts
    events:
      - eventBridge:
          eventBus: ${self:custom.settings.event_bridge_bus}
          pattern:
            source:
              - ${self:custom.settings.event_bridge_source}
            detail-type:
              - GEO_LOCATION_REGISTERED_OWNER_CHANGED
              - GEO_CREATE_DIRECTIONS
              - TR_CREATED
